import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CalendarRange, Check, FileSpreadsheet, FileText, Image, Images, Loader2, MapPin, Paperclip, Sparkles, Video, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Conversation, ConversationContent, ConversationScrollButton } from "@/components/ai-elements/conversation";
import { Message, MessageContent, MessageResponse } from "@/components/ai-elements/message";
import { PromptInput, PromptInputActionAddAttachments, PromptInputActionMenu, PromptInputActionMenuContent, PromptInputActionMenuItem, PromptInputActionMenuTrigger, PromptInputFooter, PromptInputSubmit, PromptInputTextarea, PromptInputTools, usePromptInputAttachments, type PromptInputMessage } from "@/components/ai-elements/prompt-input";
import { AiMark, IMAGES } from "./shared";
import { CONTEXT_SOURCES, MEDIA_LIBRARY, MONTHS, generateAll, ideasFor, parseTimeframe, readDirection, useLibrary, type Direction } from "@/lib/contentLibrary";

type Phase = "setup" | "discovery" | "plan" | "generating" | "ready";
const NOW = 8;
const STEPS = ["Mapping every campaign", "Writing for Direct guests", "Adapting for OTA guests", "Matching seasonal imagery", "Preparing Email and Text", "Building the release"];

function ComposerAttachments() {
  const { files, remove } = usePromptInputAttachments();
  if (!files.length) return null;
  return <div className="flex gap-2 overflow-x-auto px-3 pt-3">{files.map((file) => <div key={file.id} className="flex shrink-0 items-center gap-2 rounded-md border border-border bg-muted/45 px-2.5 py-2 text-[11.5px] text-card-foreground"><FileText size={13} className="text-brand" /><span className="max-w-36 truncate">{file.filename ?? "Attachment"}</span><Button type="button" variant="ghost" size="icon-sm" aria-label={`Remove ${file.filename ?? "attachment"}`} onClick={() => remove(file.id)}><X size={13} /></Button></div>)}</div>;
}

export function AiCreateStudio({ onClose, onReview, onPublish }: { onClose: () => void; onReview: () => void; onPublish: (range: string) => void }) {
  const { campaigns } = useLibrary();
  const [phase, setPhase] = useState<Phase>("setup");
  const [range, setRange] = useState({ s: NOW, e: NOW + 2 });
  const [direction, setDirection] = useState<Direction>({ tone: ["warm"], avoid: [], notes: [] });
  const [messages, setMessages] = useState<{ role: "user" | "assistant"; text: string }[]>([]);
  const [step, setStep] = useState(0);
  const ideas = useMemo(() => ideasFor(range.s, range.e), [range]);
  const rangeLabel = `${MONTHS[range.s]} 2026 → ${MONTHS[range.e]} 2026`;

  useEffect(() => { if (phase !== "generating") return; if (step < STEPS.length) { const timer = window.setTimeout(() => setStep((value) => value + 1), 620); return () => window.clearTimeout(timer); } const timer = window.setTimeout(() => setPhase("ready"), 450); return () => window.clearTimeout(timer); }, [phase, step]);

  const submit = (message: PromptInputMessage) => {
    const text = message.text.trim();
    if (!text && !message.files.length) return;
    const parsed = parseTimeframe(text);
    if (parsed) setRange(parsed);
    if (text) setDirection((value) => readDirection(text, value));
    const attachmentNote = message.files.length ? ` I’ll use ${message.files.length} attached file${message.files.length === 1 ? "" : "s"} as planning context.` : "";
    setMessages((value) => [...value, { role: "user", text: text || `Use the ${message.files.length} attached file${message.files.length === 1 ? "" : "s"}.` }, { role: "assistant", text: `${parsed ? `I updated the release to ${MONTHS[parsed.s]}–${MONTHS[parsed.e]}. ` : ""}I’ll reflect that across the campaign plan.${attachmentNote}` }]);
  };
  const generate = () => { generateAll(ideas, direction, rangeLabel); setStep(0); setPhase("generating"); };

  return <section aria-label="AI content planner" className="relative mt-6 overflow-hidden rounded-lg border border-brand/20 bg-card shadow-lift">
    <div className="pointer-events-none absolute inset-0 ai-grid opacity-30 [mask-image:linear-gradient(to_bottom,black,transparent_80%)]" />
    <header className="relative flex items-center justify-between border-b border-border bg-card/85 px-4 py-3 backdrop-blur-md sm:px-6"><div className="flex items-center gap-3"><AiMark size={34} live={phase === "generating"} /><div><p className="text-[13.5px] font-semibold text-card-foreground">Edit content with AI</p><p className="text-[11px] text-muted-foreground">Building a release for Holiday Inn Times Square</p></div></div><Button variant="ghost" size="icon" onClick={onClose} disabled={phase === "generating"} aria-label="Close AI planner"><X /></Button></header>

    {phase === "generating" || phase === "ready" ? <Generation phase={phase} step={step} total={campaigns.length} rangeLabel={rangeLabel} onReview={onReview} onPublish={() => onPublish(rangeLabel)} /> : <>
      <Conversation className="relative h-[min(64vh,680px)] min-h-[470px]"><ConversationContent className="mx-auto w-full max-w-5xl gap-6 px-4 pb-8 pt-8 sm:px-6">
        <section className="text-center"><span className="ai-float inline-block"><AiMark size={50} live /></span><h2 className="mt-4 font-display text-[30px] font-semibold text-card-foreground sm:text-[38px]">Let’s personalize your guest content</h2><p className="mx-auto mt-2 max-w-xl text-[14px] leading-relaxed text-muted-foreground">Reach the right guests at the right moment with a release shaped around your hotel, season, and booking journey.</p></section>
        <section className="rounded-lg border border-border bg-card p-5 shadow-card"><div className="flex items-center gap-2"><CalendarRange size={17} className="text-brand" /><p className="text-[13px] font-semibold text-card-foreground">When should this content run?</p></div><div className="mt-4 flex flex-wrap items-center gap-3"><label className="text-[11px] font-medium text-muted-foreground">From <select value={range.s} onChange={(event) => setRange((current) => ({ s: Number(event.target.value), e: Math.max(Number(event.target.value), current.e) }))} className="ml-2 h-9 rounded-md border border-border bg-background px-3 text-[12.5px] font-semibold text-card-foreground">{MONTHS.map((month, index) => index >= NOW && <option key={month} value={index}>{month} 2026</option>)}</select></label><ArrowRight size={14} className="text-muted-foreground" /><label className="text-[11px] font-medium text-muted-foreground">Until <select value={range.e} onChange={(event) => setRange((current) => ({ s: Math.min(current.s, Number(event.target.value)), e: Number(event.target.value) }))} className="ml-2 h-9 rounded-md border border-border bg-background px-3 text-[12.5px] font-semibold text-card-foreground">{MONTHS.map((month, index) => index >= NOW && <option key={month} value={index}>{month} 2026</option>)}</select></label><Button variant="brand" className="ml-auto" onClick={() => setPhase("discovery")}>Build my plan <ArrowRight /></Button></div></section>
        {phase !== "setup" && <Message from="assistant"><MessageContent><MessageResponse>{`I’ve prepared the strongest opportunities for ${rangeLabel}. They support the guest journey instead of overwhelming it.`}</MessageResponse></MessageContent></Message>}
        {phase !== "setup" && <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{ideas.slice(0, 5).map((idea) => <article key={idea.id} className="overflow-hidden rounded-md border border-border bg-card shadow-card"><div className="flex h-24 items-end bg-brand-soft p-3"><span className="text-3xl">{idea.emoji}</span></div><div className="p-3"><div className="flex items-center justify-between gap-2"><p className="text-[13px] font-semibold text-card-foreground">{idea.name}</p><span className="text-[10px] text-muted-foreground">{idea.date}</span></div><p className="mt-1 text-[11.5px] text-muted-foreground">{idea.fit}</p></div></article>)}</section>}
        {messages.map((message, index) => <Message key={`${message.role}-${index}`} from={message.role}><MessageContent><MessageResponse>{message.text}</MessageResponse></MessageContent></Message>)}
        {phase === "plan" && <><Message from="assistant"><MessageContent><MessageResponse>Here is exactly how I’ll build the release. You can adjust it or approve it as it stands.</MessageResponse></MessageContent></Message><Plan rangeLabel={rangeLabel} campaigns={campaigns.length} ideas={ideas} tone={direction.tone} onAdjust={() => setPhase("discovery")} onApprove={generate} /></>}
        {phase === "discovery" && <div className="flex justify-end"><Button variant="brand" onClick={() => setPhase("plan")}>Review full plan <ArrowRight /></Button></div>}
      </ConversationContent><ConversationScrollButton /></Conversation>
      <Composer onSubmit={submit} />
    </>}
  </section>;
}

function Plan({ rangeLabel, campaigns, ideas, tone, onAdjust, onApprove }: { rangeLabel: string; campaigns: number; ideas: ReturnType<typeof ideasFor>; tone: string[]; onAdjust: () => void; onApprove: () => void }) {
  return <section className="overflow-hidden rounded-lg border border-brand/30 bg-card shadow-lift"><div className="ai-surface border-b border-brand/15 p-5"><p className="text-[10.5px] font-semibold uppercase text-brand">Release plan · ready for review</p><div className="mt-1 flex flex-wrap items-end justify-between gap-3"><h3 className="font-display text-[22px] font-semibold text-card-foreground">{rangeLabel}</h3><span className="rounded-sm bg-brand-soft px-2 py-1 text-[11px] font-semibold text-brand">{campaigns} campaigns · Direct + OTA</span></div></div><div className="grid gap-0 lg:grid-cols-2"><div className="border-b border-border p-5 lg:border-b-0 lg:border-r"><h4 className="flex items-center gap-2 text-[13px] font-semibold text-card-foreground"><MapPin size={15} className="text-brand" />Moments I’ll weave in</h4><div className="mt-3 space-y-2">{ideas.slice(0, 4).map((idea) => <div key={idea.id} className="flex items-center gap-3 rounded-md bg-muted/45 p-2.5"><span className="text-xl">{idea.emoji}</span><div className="min-w-0 flex-1"><p className="text-[12px] font-semibold text-card-foreground">{idea.name}</p><p className="truncate text-[10.5px] text-muted-foreground">{idea.fit}</p></div><span className="text-[10px] text-muted-foreground">{idea.date}</span></div>)}</div></div><div className="p-5"><h4 className="flex items-center gap-2 text-[13px] font-semibold text-card-foreground"><Images size={15} className="text-brand" />Creative direction</h4><div className="mt-3 grid grid-cols-3 gap-2">{MEDIA_LIBRARY.slice(0, 3).map((media) => <div key={media.id}><img src={IMAGES[media.image ?? "lobby"]} alt="" className="aspect-[4/3] w-full rounded-md object-cover" /><p className="mt-1 truncate text-[10px] text-muted-foreground">{media.name}</p></div>)}</div><ul className="mt-4 space-y-2 text-[11.5px] text-card-foreground"><li>• Warm Image + CTA template for seasonal emails</li><li>• Concise one-link text messages for mobile</li><li>• {tone.join(" + ")} voice, informed by winning return campaigns</li><li>• Hotel details, existing content, and {CONTEXT_SOURCES.length - 2} other signals</li></ul></div></div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-border p-4"><p className="text-[11px] text-muted-foreground">Nothing changes until this release is published.</p><div className="flex gap-2"><Button variant="ghost" onClick={onAdjust}>Adjust</Button><Button variant="brand" onClick={onApprove}><Check />Approve plan</Button></div></div></section>;
}

function Composer({ onSubmit }: { onSubmit: (message: PromptInputMessage) => void }) {
  return <div className="relative border-t border-border bg-card/90 px-4 py-3 backdrop-blur-md"><div className="mx-auto max-w-4xl"><TooltipProvider><PromptInput accept="image/*,video/*,.pdf,.doc,.docx,.csv,.xls,.xlsx" multiple maxFiles={8} onSubmit={onSubmit} className="rounded-lg shadow-lift"><ComposerAttachments /><PromptInputTextarea placeholder="Add hotel context, instructions, or a date range…" /><PromptInputFooter><PromptInputTools><PromptInputActionMenu><PromptInputActionMenuTrigger tooltip="Add context" /><PromptInputActionMenuContent><PromptInputActionAddAttachments label="Upload files"><Paperclip />Upload files</PromptInputActionAddAttachments><PromptInputActionMenuItem><FileSpreadsheet />Spreadsheet or CSV</PromptInputActionMenuItem><PromptInputActionMenuItem><FileText />Document</PromptInputActionMenuItem><PromptInputActionMenuItem><Image />Image</PromptInputActionMenuItem><PromptInputActionMenuItem><Video />Video</PromptInputActionMenuItem></PromptInputActionMenuContent></PromptInputActionMenu><span className="hidden text-[11px] text-muted-foreground sm:inline">Documents, sheets, images, and video</span></PromptInputTools><PromptInputSubmit status="ready" /></PromptInputFooter></PromptInput></TooltipProvider></div></div>;
}

function Generation({ phase, step, total, rangeLabel, onReview, onPublish }: { phase: Phase; step: number; total: number; rangeLabel: string; onReview: () => void; onPublish: () => void }) {
  const ready = phase === "ready";
  return <main className="relative min-h-[560px] overflow-hidden p-5 sm:p-9"><div className="pointer-events-none absolute inset-0 ai-surface opacity-70" /><section className="relative mx-auto max-w-5xl"><div className="flex flex-col items-center py-6 text-center"><AiMark size={58} live={!ready} /><p className="mt-5 text-[11px] font-semibold uppercase text-brand">{ready ? "Release ready" : "Creating your release"}</p><h2 className="mt-1 font-display text-[28px] font-semibold text-card-foreground sm:text-[36px]">{ready ? `Generated content for ${rangeLabel}` : STEPS[Math.min(step, STEPS.length - 1)]}</h2><p className="mt-2 max-w-lg text-[13px] text-muted-foreground">{ready ? "Review any campaign you want, or publish the complete release now." : "Directful AI is building connected content across the complete guest journey."}</p></div><div className="grid gap-2 sm:grid-cols-3">{STEPS.map((label, index) => <div key={label} className={`relative overflow-hidden rounded-md border px-3 py-3 text-[12px] ${index < step || ready ? "border-brand/20 bg-card text-card-foreground" : index === step ? "border-brand bg-brand-soft text-brand" : "border-border bg-card/60 text-muted-foreground"}`}>{index === step && !ready && <span className="absolute inset-x-0 bottom-0 h-0.5 bg-brand [animation:ai-sweep_1.2s_ease-in-out_infinite]" />}<span className="flex items-center gap-2">{index < step || ready ? <Check size={13} className="text-brand" /> : index === step ? <Loader2 size={13} className="animate-spin" /> : <span className="size-3" />}{label}</span></div>)}</div>{ready && <div className="mt-6 flex flex-wrap items-center gap-3 rounded-lg border border-brand/25 bg-card p-5 shadow-lift"><span className="grid size-10 place-items-center rounded-md bg-brand-soft text-brand"><Sparkles size={18} /></span><div className="min-w-52 flex-1"><p className="text-[13px] font-semibold text-card-foreground">{total} campaigns are ready</p><p className="text-[11.5px] text-muted-foreground">Review is optional. Publishing makes the full release live for the selected timeframe.</p></div><Button variant="outline" onClick={onReview}>Review campaigns</Button><Button variant="brand" onClick={onPublish}>Publish release <ArrowRight /></Button></div>}</section></main>;
}
